import os.path

Import("env")
env = env.Clone()
env.Append(
    NIMCFLAGS = ["--define:release"],
)

footprints = []

for nim_file in env.Glob("*.nim"):
    base = os.path.splitext(str(nim_file))[0]
    executable = env.Nim(base + ".generate", nim_file)
    footprint = env.Command(base + ".fp", executable, "$SOURCE $TARGET")
    env.PCBRenderEPS(footprint)
    Clean(executable, "nimcache")

    footprints.append(footprint)

Export("footprints")
